"""
Alembic Migration Environment Configuration

This file is auto-generated by Alembic and configures the migration environment.
It defines how migrations are run in both offline and online modes.

Key responsibilities:
- Import all ORM models for autogenerate support
- Configure database connection
- Define migration execution modes (offline/online)

Note: This file is customized to import our models (TodoORM) so that
Alembic can detect schema changes for automatic migration generation.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Import Base and all ORM models for autogenerate support
# This allows Alembic to detect schema changes automatically
from app.database import Base
from app.models import TodoORM

# Alembic Config object provides access to values in alembic.ini
config = context.config

# Configure Python logging based on alembic.ini settings
# This enables logging during migration execution
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set target metadata to our Base.metadata
# This tells Alembic which models to track for schema changes
# The metadata contains all table definitions from our ORM models
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.
    
    Offline mode generates SQL scripts without connecting to the database.
    This is useful for:
    - Generating migration SQL for manual review
    - Applying migrations in restricted environments
    - Creating SQL files for DBA review
    
    In offline mode:
    - No database connection is created
    - SQL statements are output to stdout
    - No actual database changes are made
    
    Usage:
        alembic upgrade head --sql > migration.sql
    """
    # Get database URL from alembic.ini
    url = config.get_main_option("sqlalchemy.url")
    
    # Configure Alembic context with URL only (no Engine needed)
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,  # Include literal parameter values in SQL
        dialect_opts={"paramstyle": "named"},  # Use named parameters
    )

    # Execute migrations and output SQL statements
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.
    
    Online mode connects to the database and applies migrations directly.
    This is the default mode when running alembic commands.
    
    In online mode:
    - A database connection is established
    - Migrations are applied to the database immediately
    - Changes are committed to the database
    
    Usage:
        alembic upgrade head
        alembic downgrade -1
    """
    # Create SQLAlchemy engine from alembic.ini configuration
    # NullPool is used to avoid connection pooling issues with SQLite
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    # Establish connection and run migrations
    with connectable.connect() as connection:
        # Configure Alembic context with active database connection
        context.configure(connection=connection, target_metadata=target_metadata)

        # Execute migrations within a transaction
        with context.begin_transaction():
            context.run_migrations()


# Determine mode and execute appropriate migration function
# Offline mode: generates SQL without database connection
# Online mode: applies migrations directly to database
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
