"""
Initial Todo Microservice Database Schema Migration

This is the first Alembic migration for the Todo microservice.
It creates the 'todos' table with all necessary columns.

Migration Info:
    Revision ID: 67efd1b204a6
    Revises: None (initial migration)
    Create Date: 2026-09-22 15:39:26.368409

Database Pattern:
    - Database-per-service pattern: Each microservice owns its own database
    - No foreign keys to other services (ensuring service independence)
    - UUID primary keys for globally unique identifiers

To Apply:
    alembic upgrade head

To Rollback:
    alembic downgrade -1
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers used by Alembic for tracking migration history
# revision: unique ID for this migration
# down_revision: previous migration (None means this is the first)
# branch_labels: optional labels for branching migrations
# depends_on: migrations from other services this depends on (None for service independence)
revision: str = '67efd1b204a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply the migration: Create the todos table.
    
    This migration creates the main todos table with:
    - id: UUID primary key (globally unique identifier)
    - title: Required string field for todo title (max 100 chars)
    - description: Optional string field for details (max 255 chars)
    - completed: Boolean flag for completion status (default False)
    
    The UUID type ensures unique IDs even across distributed systems,
    which is important in microservices architecture where IDs might
    be generated independently.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.UUID(), nullable=False),  # Primary key: UUID for global uniqueness
    sa.Column('title', sa.String(length=100), nullable=False),  # Required: todo title
    sa.Column('description', sa.String(length=255), nullable=True),  # Optional: todo details
    sa.Column('completed', sa.Boolean(), nullable=True),  # Completion status
    sa.PrimaryKeyConstraint('id')  # Define id as primary key
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback the migration: Drop the todos table.
    
    WARNING: This will delete all todo data! Use with caution.
    
    In production, consider implementing a safer rollback strategy
    such as:
    - Archiving data before dropping tables
    - Using soft deletes instead of hard drops
    - Creating backup before running downgrade
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')  # Remove the todos table and all data
    # ### end Alembic commands ###
