"""Initial modular monolith schema

This migration creates the initial database schema for the modular monolith
Todo application. It sets up the todos_todo table with all necessary fields.

Revision ID: e893d74119ac
Revises: 
Create Date: 2026-09-22 12:53:17.309005

Migration Details:
- Creates the todos_todo table
- Uses UUID for primary key (better for distributed systems)
- Includes title (required), description (optional), and completed status
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic for tracking migration history
revision: str = 'e893d74119ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema to initial version.
    
    Creates the todos_todo table with:
    - id: UUID primary key
    - title: Required string (max 100 chars)
    - description: Optional string (max 255 chars)
    - completed: Boolean flag (defaults to False)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos_todo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema to previous version.
    
    Removes the todos_todo table and all its data.
    WARNING: This is a destructive operation!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos_todo')
    # ### end Alembic commands ###
