# app/services/todo_service.py
"""
Todo Service Layer Module

This module implements the business logic for Todo operations.
The service layer pattern separates business logic from GraphQL resolvers,
providing several benefits:

1. Separation of Concerns: Resolvers handle GraphQL, services handle business logic
2. Reusability: Services can be used by multiple resolvers or other services
3. Testability: Services can be unit tested independently
4. Maintainability: Business logic is centralized in one place

Design Pattern: Service Layer (Business Logic Layer)
"""

from uuid import UUID
from sqlalchemy.orm import Session
from app.models import TodoORM


class TodoService:
    """
    Service class for Todo-related business operations.
    
    This class encapsulates all Todo-related business logic and database
    operations, keeping GraphQL resolvers thin and focused.
    
    Attributes:
        db (Session): SQLAlchemy database session for executing queries
        
    Design Principles:
    - Single Responsibility: Handles only Todo operations
    - Dependency Injection: Database session injected via constructor
    - Explicit over Implicit: Clear method signatures and return types
    """
    
    def __init__(self, db: Session):
        """
        Initialize TodoService with a database session.
        
        Args:
            db (Session): SQLAlchemy database session
            
        Note: The session is managed by FastAPI's dependency injection
        and automatically closed after the request completes.
        """
        self.db = db

    def create_todo(self, title: str, user_id: UUID) -> TodoORM:
        """
        Create a new Todo item in the database.
        
        This method handles the creation of a new todo, including:
        1. Creating the ORM instance
        2. Adding it to the database session
        3. Committing the transaction
        4. Refreshing to get the generated ID
        
        Args:
            title (str): The todo description/title
            user_id (UUID): The ID of the user who owns this todo
            
        Returns:
            TodoORM: The newly created todo with generated ID
            
        Raises:
            IntegrityError: If user_id doesn't exist (foreign key constraint)
            
        Example:
            service = TodoService(db)
            todo = service.create_todo(
                title="Buy groceries",
                user_id=UUID("123e4567-e89b-12d3-a456-426614174000")
            )
            print(todo.id)  # Generated UUID
            
        Database Operations:
            1. INSERT INTO todos (id, title, user_id) VALUES (...)
        """
        # Create a new TodoORM instance
        # The UUID is auto-generated by the default=uuid.uuid4 in the model
        todo = TodoORM(title=title, user_id=user_id)
        
        # Add the instance to the session (staged for insertion)
        self.db.add(todo)
        
        # Commit the transaction to persist to the database
        # This executes the INSERT statement
        self.db.commit()
        
        # Refresh to get the generated ID and any database defaults
        # This executes a SELECT to fetch the fresh state
        self.db.refresh(todo)
        
        return todo

    def update_todo(
        self, id: UUID, title: str | None = None, completed: bool | None = None
    ) -> TodoORM:
        """
        Update an existing Todo item.
        
        Supports partial updates - only provided fields are modified.
        This follows the PATCH semantics (vs PUT which replaces entirely).
        
        Args:
            id (UUID): The ID of the todo to update
            title (str | None): New title (optional, None = no change)
            completed (bool | None): Completion status (optional, None = no change)
            
        Returns:
            TodoORM: The updated todo with all current values
            
        Raises:
            ValueError: If todo with given ID doesn't exist
            
        Example:
            service = TodoService(db)
            
            # Update only the title
            todo = service.update_todo(
                id=todo_id,
                title="Buy organic groceries"
            )
            
            # Update only completion status
            todo = service.update_todo(
                id=todo_id,
                completed=True
            )
            
            # Update both fields
            todo = service.update_todo(
                id=todo_id,
                title="Buy organic groceries",
                completed=True
            )
            
        Database Operations:
            1. SELECT * FROM todos WHERE id = ?
            2. UPDATE todos SET ... WHERE id = ?
            3. SELECT * FROM todos WHERE id = ? (refresh)
        """
        # Query for the todo by ID
        # .first() returns None if not found (vs .one() which raises exception)
        todo = self.db.query(TodoORM).filter(TodoORM.id == id).first()
        
        # Validate that the todo exists
        if not todo:
            raise ValueError(f"Todo with ID '{id}' not found.")

        # Apply partial updates only for provided fields
        # This allows clients to update only specific fields
        if title is not None:
            todo.title = title
            
        if completed is not None:
            todo.completed = completed

        # Commit the changes to the database
        # SQLAlchemy tracks modifications automatically (dirty checking)
        self.db.commit()
        
        # Refresh to ensure we return the latest state
        self.db.refresh(todo)
        
        return todo

    def delete_todo(self, id: UUID) -> bool:
        """
        Delete a Todo item from the database.
        
        This is a hard delete (permanent removal from the database).
        For production applications, consider soft deletes instead:
        - Add a 'deleted_at' timestamp field
        - Filter out deleted records in queries
        - Allows data recovery and audit trails
        
        Args:
            id (UUID): The ID of the todo to delete
            
        Returns:
            bool: True if deleted successfully, False if todo not found
            
        Example:
            service = TodoService(db)
            
            success = service.delete_todo(todo_id)
            if success:
                print("Todo deleted")
            else:
                print("Todo not found")
                
        Database Operations:
            1. SELECT * FROM todos WHERE id = ?
            2. DELETE FROM todos WHERE id = ?
            
        Note: This operation is destructive and cannot be undone.
        """
        # Query for the todo by ID
        todo = self.db.query(TodoORM).filter(TodoORM.id == id).first()
        
        # If todo doesn't exist, return False (not an error)
        if not todo:
            return False

        # Mark the object for deletion
        self.db.delete(todo)
        
        # Commit the transaction to execute the DELETE
        self.db.commit()
        
        # Return True to indicate successful deletion
        return True
