"""
Initial Audit Microservice Database Schema Migration

This is the first Alembic migration for the Audit microservice.
It creates the 'audit_logs' table for centralized event logging.

Migration Info:
    Revision ID: fce904d8a158
    Revises: None (initial migration)
    Create Date: 2026-09-22 15:01:46.359185

Architecture Pattern:
    - Event-Driven Architecture: Captures events from other microservices
    - Centralized Audit Logging: Single source of truth for all system events
    - Database-per-service: Audit service owns its audit.db database
    - Immutable Audit Trail: No update/delete operations on audit logs

To Apply:
    alembic upgrade head

To Rollback:
    alembic downgrade -1
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers used by Alembic for tracking migration history
# revision: unique ID for this migration
# down_revision: previous migration (None means this is the first)
# branch_labels: optional labels for branching migrations
# depends_on: migrations from other services this depends on (None for independence)
revision: str = 'fce904d8a158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply the migration: Create the audit_logs table.
    
    This migration creates the audit_logs table for storing events from
    all microservices in the system. This demonstrates the event-driven
    architecture pattern where services publish events to a central log.
    
    Table Structure:
    - id: UUID primary key (globally unique identifier)
    - event_type: Type of event (e.g., "TODO_CREATED", "TODO_DELETED")
    - resource_id: ID of the affected resource (e.g., todo UUID)
    - message: Human-readable description of what happened
    - created_at: Timestamp when the event occurred (UTC)
    
    Design Considerations:
    - Immutable logs: No foreign keys or update operations
    - UTC timestamps: All times stored in UTC for consistency
    - String IDs: resource_id is string to support different ID formats
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),  # Primary key: UUID for global uniqueness
    sa.Column('event_type', sa.String(length=50), nullable=False),  # Event type: e.g., "TODO_CREATED"
    sa.Column('resource_id', sa.String(length=100), nullable=False),  # Affected resource ID
    sa.Column('message', sa.String(length=255), nullable=False),  # Human-readable description
    sa.Column('created_at', sa.DateTime(), nullable=True),  # Event timestamp (UTC)
    sa.PrimaryKeyConstraint('id')  # Define id as primary key
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback the migration: Drop the audit_logs table.
    
    WARNING: This will delete all audit history! Use with extreme caution.
    
    In production, audit logs should often be:
    - Archived before deletion (compliance requirements)
    - Exported to long-term storage (S3, data warehouse)
    - Never deleted (immutable audit trail for compliance)
    
    Consider using soft deletes or archive patterns instead of hard drops
    for audit data.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')  # Remove the audit_logs table and all data
    # ### end Alembic commands ###
